-- Optional for deployments that manage schema manually (PostgreSQL).
-- Hibernate ddl-auto=update also adds these columns and the support_tickets table.
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_visible boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS message_requests_enabled boolean DEFAULT true;
CREATE TABLE IF NOT EXISTS support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner varchar(36) NOT NULL, category varchar(20) NOT NULL,
  subject varchar(120) NOT NULL, message varchar(2000) NOT NULL,
  status varchar(20) NOT NULL, reply varchar(2000),
  created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone
);
CREATE INDEX IF NOT EXISTS idx_support_owner_created ON support_tickets(owner,created_at);
