spring.application.name=linkup-api


spring.main.allow-circular-references=true
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/LINKUP
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create


